[package]
name = "bitreel"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
hyper = {version = "0.9", default-features = false}
lazy_static = "0.2"
regex = "0.1"

[features]
ssl = ["hyper/ssl"]
